export { default as user } from '#routers/masters/UserRoute'
export { default as variable } from '#routers/masters/VariableRoute'
export { default as subVariable } from '#routers/masters/SubVariableRoute'
export { default as indicator } from '#routers/masters/IndicatorRoute'
export { default as factor } from '#routers/masters/FactorRoute'